######################################################################
# Automatically generated by qmake (2.01a) Sun May 31 21:35:52 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += glwidget.h snap.h window.h
SOURCES += glwidget.cpp main.cpp snap.cpp window.cpp
QT		+=	opengl
