######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 12 15:22:02 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += glwidget.h snap.h window.h
SOURCES += glwidget.cpp main.cpp snap.cpp window.cpp
QT		+= opengl
